apiVersion: v1
kind: Pod
metadata:
  name: cpu-model-nfd
spec:
  restartPolicy: OnFailure
  initContainers:
    - image: quay.io/ksimon/cpu-model-nfd-plugin:latest
      command: ["/bin/sh","-c"]
      args: ["cp /plugin/dest/cpu-model-nfd-plugin /host-hook/cpu-model-nfd-plugin"]
      imagePullPolicy: Always
      name: cpu-model-nfd-plugin
      securityContext:
        privileged: true
      volumeMounts:
        - name: nfd-hook
          mountPath: "/host-hook"
  containers:
    - name: kubevirt-libvirt
      image: kubevirt/libvirt
      command: ["/bin/sh","-c"]
      args: ["libvirtd -d; chmod o+rw /dev/kvm; virsh domcapabilities > /host-hook/virsh_domcapabilities.xml;"]
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: nfd-hook
          mountPath: "/host-hook"
      resources:
        requests:
          devices.kubevirt.io/kvm: "1"
        limits:
          devices.kubevirt.io/kvm: "1"
  volumes:
    - name: nfd-hook
      hostPath:
        path: "/opt/lib/node-feature-discovery/source.d"